name: flutter_pagination_pro
description: "A lightweight, zero-dependency Flutter pagination toolkit. Infinite scroll, load more, grid, slivers, numbered pages, bidirectional, animated lists, skeleton loading & keyboard nav"
version: 1.0.2
homepage: https://github.com/Masum-MSNR/flutter_pagination_pro
repository: https://github.com/Masum-MSNR/flutter_pagination_pro
issue_tracker: https://github.com/Masum-MSNR/flutter_pagination_pro/issues

topics:
  - pagination
  - infinite-scroll
  - lazy-loading
  - listview
  - gridview

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  matcher: ">=0.12.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
